MODEL:
  META_ARCHITECTURE: "panoptic_deeplab"
  BN_MOMENTUM: 0.01
  BACKBONE:
    NAME: "resnet50"
    DILATION: (False, False, False)
    PRETRAINED: False
    USE_DEEP_STEM: True
    DEEP_STEM: ( 32, 16 ,16 )
    INPUT_CHANNELS: 16
  DECODER:
    IN_CHANNELS: 2048
    FEATURE_KEY: "res4"
    DECODER_CHANNELS: 256
    ATROUS_RATES: (3, 6, 9)
  PANOPTIC_DEEPLAB:
    LOW_LEVEL_KEY: [ "res3", "res2", "stem" ]
    INSTANCE:
      ENABLE: True
      LOW_LEVEL_CHANNELS_PROJECT: (32, 16)
      DECODER_CHANNELS: 64
      HEAD_CHANNELS: 32
      ASPP_CHANNELS: 128
      NUM_CLASSES: (1, 2)
      CLASS_KEY: [ "center", "offset" ]
DATASET:
  ROOT: "datasets/cityscapes"
  DATASET: "cityscapes_panoptic"
  NUM_CLASSES: 19
  TRAIN_SPLIT: 'train'
  TEST_SPLIT: 'val'
  CROP_SIZE: (768, 1536)
  MIRROR: True
  MIN_SCALE: 0.5
  MAX_SCALE: 2.0
  SCALE_STEP_SIZE: 0.1
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  SEMANTIC_ONLY: False
  IGNORE_STUFF_IN_OFFSET: True
  SMALL_INSTANCE_AREA: 4096
  SMALL_INSTANCE_WEIGHT: 3
  PRE_AUG: (768, 1536)
  TRANSFORM_TO_USE: 0
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_BIAS: 0.0
  OPTIMIZER: "adam"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  WARMUP_ITERS: 0
LOSS:
  SEMANTIC:
    NAME: "hard_pixel_mining"
    IGNORE: 255
    TOP_K_PERCENT: 0.2
    WEIGHT: 2.0
  CENTER:
    NAME: "mse"
    WEIGHT: 200.0
  OFFSET:
    NAME: "l1"
    WEIGHT: 0.01
TRAIN:
  RESUME: False
  IMS_PER_BATCH: 16
  MAX_ITER: 8000000
DEBUG:
  DEBUG: True
  DEBUG_FREQ: 100
TEST:
  DEBUG: False
  EVAL_INSTANCE: False
  EVAL_PANOPTIC: False
  CROP_SIZE: (768, 1536)
POST_PROCESSING:
  CENTER_THRESHOLD: 0.1
  NMS_KERNEL: 7
  TOP_K_INSTANCE: 200
  STUFF_AREA: 2048
DATALOADER:
  PIN_MEMORY: True
  NUM_WORKERS: 4
OUTPUT_DIR: "./output"
GPUS: (0,1,2,3 )
CKPT_FREQ: 1000
PRINT_FREQ: 10
WORKERS: 1
